### ISSUE TITLE
Facility to disable dynamic libraries

### ISSUE THREAD

**Issue by ferronn-dev** [Meorawr/tainted-lua#8]
Stock Lua 5.1.5 provides a configuration knob to control usage of dlopen-based functionality. This is on by default when using LUA_USE_LINUX but is still a separate preprocessor symbol that can be manipulated separately.

In Elune, LUA_USE_POSIX is used as a single knob, which makes it difficult/impossible to compile Elune for POSIX while simultaneously disabling dlopen.

This is desirable for Elune installations that wish to statically link all dependencies, in particular to avoid a cranky linker warning, e.g.

```
/usr/bin/ld: /tmp/wowless.GKA9d8.ltrans4.ltrans.o: in function `unixDlOpen.lto_priv.0':
<artificial>:(.text+0x1218): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

Perhaps a separate configuration altogether is actually best, to uniformly (irrespective of POSIX or anything else) request the stub `ll_` function implementations in loadlib.c.

**Comment by Meorawr** [comment]
What specific use case do you have in mind for a fully static build where `require` and friends also don't work?

**Comment by Meorawr** [comment]
Let me know if 7fc7271 meets your needs.

**Comment by ferronn-dev** [comment]
Require continues to work; wowless simply disables filesystem checks for .so files for now, and will soon also disable filesystem checks for .lua files, leaving only preloading. https://github.com/wowless/wowless/blob/main/main.c#L39-L43

**Comment by ferronn-dev** [comment]
Also, thanks, this works like a charm. (Unfortunately, lsqlite3 isn't so well behaved.)
